# Generated by Django 3.0 on 2020-12-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20201217_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upvote',
            new_name='likes',
        ),
    ]
